### ISSUE TITLE
Persistir pré configuração do modelo

### ISSUE THREAD

**Issue by igor-paiva** [fga-eps-mds/2021-2-MeasureSoftGram-Doc#51]
## Descrição

Como engennheiro de software, gostaria de persistir a meta de configuração na camada de persistência para que possa ser utilizada posteriormente.

## Critérios de aceitação

- [ ] Persistência de configuração inválida
    - Dado que uma meta de configuração é inválida
    - Quando salvar
    - Então um erro deverá ser exibido
- [ ] Persistência de configuração válida
    - Dado que uma meta de configuração válida
    - Quando salvar
    - Então uma mensagem de sucesso deve ser exibida

## Tarefas

- [ ] Criar e configurar camada de persistência
- [ ] Criar abstração para a camada de persistência
- [ ] Criar o modelo para a meta de configuração
- [ ] Validar o modelo com validações configuradas
- [ ] Persistir o modelo na camada de persistência
- [ ] Criar endpoint para persistência

**Comment by LucasPimentel123** [comment]
Durante discussões do projeto, percebemos que esta história de usuário poderia ser incorporada pela história de Criar Pré Configuração do Modelo

**Comment by LucasPimentel123** [comment]
Durante as discussões do projeto, percebemos que esta Histórtia de Usuário poderia ser incorporada pela história de Criar Pré Configuração do Modelo
