### ISSUE TITLE
Salvar as métricas

### ISSUE THREAD

**Issue by Rhuancpq** [fga-eps-mds/2021-2-MeasureSoftGram-Doc#58]
## Descrição

Como engenheiro de software, gostaria de ter a possibilidade de salvar as métricas para uso posterior

## Critérios de aceitação

- [ ]  

## Tarefas

- [ ] Criar abstração modelo das métricas (MVC)
- [ ] Criar endpoint para salvar as métricas
- [ ] Validar os dados recebidos em relação ao modelo
- [ ] Enviar as métricas do cliente para o servidor
- [ ] Informar para o usuário o status da requisição

**Comment by LucasPimentel123** [comment]
Durante as discussões do projeto, percebemos que esta Histórtia de Usuário poderia ser incorporada pela história de Ler Métricas do Arquivo
