### ISSUE TITLE
Implementar operação de agregação

### ISSUE THREAD

**Issue by Rhuancpq** [fga-eps-mds/2021-2-MeasureSoftGram-Doc#59]
## Descrição

Como engenheiro de software, eu gostaria de poder agregar medidas em subcaracterísticas e estas em características, para poder observar o valor do indicador agregado da qualidade em diferentes níveis do modelo.

## Tarefas
- [ ]

## Critérios de aceitação

- [ ] A operação de agregação é realizada pela aplica das norma tensorial de Frobenius, em qualquer nível do modelo
- [ ] O resultado de uma agregação deve pertencer ao intervalo [a,b]={x∈ℝ:0≤x≤1}
- [ ] Poder visualizar (print na cli) os tensores com seus valores calculados e agregados.

## Observações
A quantidade	de medidas que descreve uma subcaracteristica define a quantidade de dimensões do seu respectivo tensor
A quantidade de subcaracterísticas define a quantidade de dimensões do seu tensor das características
Quando no nível das medidas, os indicadores agregados representarão um conjunto de tensores agregados de subcaracterísticas
Quando no nível das subcaracterísticas, os indicadores agregados representarão um conjunto de tensores agregados das características
Quando no nível das características, o indicador agregado descreve o total da qualidade para uma determinada configuração de software(SQC)
As medidas definidas no modelo, em1, em2 e em3 e descrevem a subcaracterística de modiafibility
As medidas definidas no modelo, em3, em4 e em5 e descrevem a subcaracterística de testing_status
As subcaracterísticas definidas, modiafibility e testing_status, descrevem respectivamente as características de maintainability e realiability.
O indicador de qualidade total(SQC) é obtido pela norma do tensor de ordem 1(vetor) de características, onde: cada posição do vetor SQC representa um indicador agregado de uma característica.
Um SQC representa uma release

**Comment by hneri** [comment]
Atualização da escrita da história, critérios de aceitação e observações.
