### ISSUE TITLE
Implementar operação de ponderação

### ISSUE THREAD

**Issue by Rhuancpq** [fga-eps-mds/2021-2-MeasureSoftGram-Doc#60]
## Descrição

Como engenheiro de software, eu gostaria de poder ponderar medidas, subcaracterísticas e características, para poder definir a importância relativa destas em todos os níveis do modelo.

## Tarefas
- [ ]

## Critérios de aceitação

- [ ] Deve realizar o produto tensorial do peso definido para as caracteristicas, subcaracteristicas e medidas, obedecendo aa seguinte ordem: 1) medidas; 2)subcaracterísticas e 3)caracteristicas (botou-up).
- [ ] Os tensores não podem ter uma quantidade maior de dimensões do que o definido no arquivo de entrada da pré-configuração (em todos os níveis)
- [ ] Os pesos devem ser recuperados a partir do arquivo que descreve a pré-configuração
- [ ] O resultado de uma ponderação deve pertencer ao intervalo [a,b]={x∈ℝ:0≤x≤1}
- [ ] Poder visualizar (_print_ na cli) os tensores com seus valores não-ponderados e ponderados (caracteristicas/subcaracteristicas/medidas) a depender do nível

## Observações

A quantidade	de medidas que descreve uma subcaracteristica define a quantidade de dimensões do seu respectivo tensor
A quantidade de subcaracterísticas define a quantidade de dimensões do seu tensor das características
Quando no nível das medidas, o produto tensorial deve ser realizado no tensor das medidas definidas, calculadas, para uma determinada subcaracterística E seus pesos correspondentes.
Quando no nível das subcaracterísticas, o produto tensorial deve ser realizado no tensor das subcaracterísticas definidas, agregadas E seus pesos correspondentes
Quando no nível das características, o produto tensorial deve ser realizado no tensor das características definidas, agregadas E seus pesos correspondentes
As medidas definidas no modelo, em1, em2 e em3 e descrevem a subcaracterística de modiafibility
As medidas definidas no modelo, em3, em4 e em5 e descrevem a subcaracterística de testing_status
As subcaracterísticas definidas, modiafibility e testing_status, descrevem respectivamente as características de maintainability e realiability.

**Comment by hneri** [comment]
Atualização da escrita da história, critérios de aceitação e observações
