### ISSUE TITLE
Criação do repositório para itens associados a instalação e execução da aplicação

### ISSUE THREAD

**Issue by Rhuancpq** [fga-eps-mds/2021-2-MeasureSoftGram-Doc#94]
## Descrição da atividade
Criar um repositório para armazenar os scripts e arquivos envolvidos a instalação e execução da aplicação como um todo

**Comment by igor-paiva** [comment]
Até o momento não será necessário um repositório, se em algum momento isso mudar esta issue pode ser reaberta.

**Comment by igor-paiva** [comment]
Até o momento não será necessário um repositório, se em algum momento isso mudar esta issue pode ser reaberta.
